version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receitas_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - receitas-net

  web:
    image: nginx:stable-alpine
    container_name: receitas_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - receitas-net

  db:
    image: mysql:8.0
    container_name: receitas_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: receitas
      MYSQL_USER: receitas
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - receitas-net

networks:
  receitas-net:
    driver: bridge

volumes:
  db_data:
